/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "naboo/model/CashOutOrangeRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



CashOutOrangeRequest::CashOutOrangeRequest()
{
    m_Full_name = utility::conversions::to_string_t("");
    m_Full_nameIsSet = false;
    m_Amount = 0;
    m_AmountIsSet = false;
    m_Phone_number = utility::conversions::to_string_t("");
    m_Phone_numberIsSet = false;
}

CashOutOrangeRequest::~CashOutOrangeRequest()
{
}

void CashOutOrangeRequest::validate()
{
    // TODO: implement validation
}

web::json::value CashOutOrangeRequest::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Full_nameIsSet)
    {
        val[utility::conversions::to_string_t(U("full_name"))] = ModelBase::toJson(m_Full_name);
    }
    if(m_AmountIsSet)
    {
        val[utility::conversions::to_string_t(U("amount"))] = ModelBase::toJson(m_Amount);
    }
    if(m_Phone_numberIsSet)
    {
        val[utility::conversions::to_string_t(U("phone_number"))] = ModelBase::toJson(m_Phone_number);
    }

    return val;
}

bool CashOutOrangeRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("full_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("full_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFullName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFullName);
            setFullName(refVal_setFullName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("amount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("amount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAmount);
            setAmount(refVal_setAmount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("phone_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("phone_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhoneNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhoneNumber);
            setPhoneNumber(refVal_setPhoneNumber);
        }
    }
    return ok;
}

void CashOutOrangeRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Full_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("full_name")), m_Full_name));
    }
    if(m_AmountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("amount")), m_Amount));
    }
    if(m_Phone_numberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("phone_number")), m_Phone_number));
    }
}

bool CashOutOrangeRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("full_name"))))
    {
        utility::string_t refVal_setFullName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("full_name"))), refVal_setFullName );
        setFullName(refVal_setFullName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("amount"))))
    {
        int32_t refVal_setAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("amount"))), refVal_setAmount );
        setAmount(refVal_setAmount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("phone_number"))))
    {
        utility::string_t refVal_setPhoneNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("phone_number"))), refVal_setPhoneNumber );
        setPhoneNumber(refVal_setPhoneNumber);
    }
    return ok;
}

utility::string_t CashOutOrangeRequest::getFullName() const
{
    return m_Full_name;
}

void CashOutOrangeRequest::setFullName(const utility::string_t& value)
{
    m_Full_name = value;
    m_Full_nameIsSet = true;
}

bool CashOutOrangeRequest::fullNameIsSet() const
{
    return m_Full_nameIsSet;
}

void CashOutOrangeRequest::unsetFull_name()
{
    m_Full_nameIsSet = false;
}
int32_t CashOutOrangeRequest::getAmount() const
{
    return m_Amount;
}

void CashOutOrangeRequest::setAmount(int32_t value)
{
    m_Amount = value;
    m_AmountIsSet = true;
}

bool CashOutOrangeRequest::amountIsSet() const
{
    return m_AmountIsSet;
}

void CashOutOrangeRequest::unsetAmount()
{
    m_AmountIsSet = false;
}
utility::string_t CashOutOrangeRequest::getPhoneNumber() const
{
    return m_Phone_number;
}

void CashOutOrangeRequest::setPhoneNumber(const utility::string_t& value)
{
    m_Phone_number = value;
    m_Phone_numberIsSet = true;
}

bool CashOutOrangeRequest::phoneNumberIsSet() const
{
    return m_Phone_numberIsSet;
}

void CashOutOrangeRequest::unsetPhone_number()
{
    m_Phone_numberIsSet = false;
}
}
}
}
}


