/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "naboo/model/GetAllTransaction.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



GetAllTransaction::GetAllTransaction()
{
    m_TransactionsIsSet = false;
}

GetAllTransaction::~GetAllTransaction()
{
}

void GetAllTransaction::validate()
{
    // TODO: implement validation
}

web::json::value GetAllTransaction::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_TransactionsIsSet)
    {
        val[utility::conversions::to_string_t(U("transactions"))] = ModelBase::toJson(m_Transactions);
    }

    return val;
}

bool GetAllTransaction::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("transactions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("transactions")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GetOneTransaction>> refVal_setTransactions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTransactions);
            setTransactions(refVal_setTransactions);
        }
    }
    return ok;
}

void GetAllTransaction::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_TransactionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("transactions")), m_Transactions));
    }
}

bool GetAllTransaction::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("transactions"))))
    {
        std::vector<std::shared_ptr<GetOneTransaction>> refVal_setTransactions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("transactions"))), refVal_setTransactions );
        setTransactions(refVal_setTransactions);
    }
    return ok;
}

std::vector<std::shared_ptr<GetOneTransaction>>& GetAllTransaction::getTransactions()
{
    return m_Transactions;
}

void GetAllTransaction::setTransactions(const std::vector<std::shared_ptr<GetOneTransaction>>& value)
{
    m_Transactions = value;
    m_TransactionsIsSet = true;
}

bool GetAllTransaction::transactionsIsSet() const
{
    return m_TransactionsIsSet;
}

void GetAllTransaction::unsetTransactions()
{
    m_TransactionsIsSet = false;
}
}
}
}
}


