/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "naboo/model/TransactionStatusEnum.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

TransactionStatusEnum::eTransactionStatusEnum toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("pending")))
        return TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_PENDING;
    if (val == utility::conversions::to_string_t(U("paid")))
        return TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_PAID;
    if (val == utility::conversions::to_string_t(U("done")))
        return TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_DONE;
    if (val == utility::conversions::to_string_t(U("part_paid")))
        return TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_PART_PAID;
    return {};
}

EnumUnderlyingType fromEnum(TransactionStatusEnum::eTransactionStatusEnum e)
{
    switch (e)
    {
    case TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_PENDING:
        return U("pending");
    case TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_PAID:
        return U("paid");
    case TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_DONE:
        return U("done");
    case TransactionStatusEnum::eTransactionStatusEnum::TransactionStatusEnum_PART_PAID:
        return U("part_paid");
    default:
        break;
    }
    return {};
}
}

TransactionStatusEnum::TransactionStatusEnum()
{
}

TransactionStatusEnum::~TransactionStatusEnum()
{
}

void TransactionStatusEnum::validate()
{
    // TODO: implement validation
}

web::json::value TransactionStatusEnum::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool TransactionStatusEnum::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void TransactionStatusEnum::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool TransactionStatusEnum::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

TransactionStatusEnum::eTransactionStatusEnum TransactionStatusEnum::getValue() const
{
   return m_value;
}

void TransactionStatusEnum::setValue(TransactionStatusEnum::eTransactionStatusEnum const value)
{
   m_value = value;
}


}
}
}
}


