/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AccountApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_AccountApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_AccountApi_H_



#include "naboo/ApiClient.h"

#include "naboo/model/GetAccountResponse.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  AccountApi 
{
public:

    explicit AccountApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~AccountApi();

    /// <summary>
    /// Get Account Information
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::shared_ptr<GetAccountResponse>> getAccountInformationAccountGet(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_AccountApi_H_ */

