/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CashoutApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_CashoutApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_CashoutApi_H_



#include "naboo/ApiClient.h"

#include "naboo/model/CashOutOrangeRequest.h"
#include "naboo/model/CashOutResponse.h"
#include "naboo/model/CashOutWaveRequest.h"
#include "naboo/model/HTTPValidationError.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  CashoutApi 
{
public:

    explicit CashoutApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CashoutApi();

    /// <summary>
    /// Cash Out Orange Money
    /// </summary>
    /// <remarks>
    /// This endpoint enables a user to withdraw funds from their NabooPay account to their Orange Money account. Authentication is required, and users with the &#39;dev&#39; role are not permitted to perform this operation. The amount to be withdrawn must be positive and within the user&#39;s available balance. The user&#39;s account must be active and registered in the system. After validation, the user&#39;s account balance is adjusted accordingly, and the transaction is logged for record-keeping.
    /// </remarks>
    /// <param name="cashOutOrangeRequest"></param>
    pplx::task<std::shared_ptr<CashOutResponse>> cashOutOrangeMoneyCashoutOrangeMoneyPost(
        std::shared_ptr<CashOutOrangeRequest> cashOutOrangeRequest
    ) const;
    /// <summary>
    /// Cash Out Wave
    /// </summary>
    /// <remarks>
    /// This endpoint allows a user to withdraw funds from their NabooPay account to their Wave account. The user must be authenticated and not possess the &#39;dev&#39; role. The withdrawal amount must be greater than 10 and not exceed the user&#39;s account balance. The user&#39;s account must exist and be active. Upon successful validation, the system updates the user&#39;s account balance and records the transaction for tracking purposes.
    /// </remarks>
    /// <param name="cashOutWaveRequest"></param>
    pplx::task<std::shared_ptr<CashOutResponse>> cashOutWaveCashoutWavePost(
        std::shared_ptr<CashOutWaveRequest> cashOutWaveRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_CashoutApi_H_ */

