/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CashOutResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CashOutResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CashOutResponse_H_


#include "naboo/ModelBase.h"

#include "naboo/model/TransactionStatusEnum.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  CashOutResponse
    : public ModelBase
{
public:
    CashOutResponse();
    virtual ~CashOutResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CashOutResponse members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPhoneNumber() const;
    bool phoneNumberIsSet() const;
    void unsetPhone_number();

    void setPhoneNumber(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getAmount() const;
    bool amountIsSet() const;
    void unsetAmount();

    void setAmount(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFullName() const;
    bool fullNameIsSet() const;
    void unsetFull_name();

    void setFullName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<TransactionStatusEnum> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const std::shared_ptr<TransactionStatusEnum>& value);


protected:
    utility::string_t m_Phone_number;
    bool m_Phone_numberIsSet;
    int32_t m_Amount;
    bool m_AmountIsSet;
    utility::string_t m_Full_name;
    bool m_Full_nameIsSet;
    std::shared_ptr<TransactionStatusEnum> m_Status;
    bool m_StatusIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CashOutResponse_H_ */
