/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetAllTransaction.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GetAllTransaction_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GetAllTransaction_H_


#include "naboo/ModelBase.h"

#include "naboo/model/GetOneTransaction.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class GetOneTransaction;


/// <summary>
/// 
/// </summary>
class  GetAllTransaction
    : public ModelBase
{
public:
    GetAllTransaction();
    virtual ~GetAllTransaction();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GetAllTransaction members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<GetOneTransaction>>& getTransactions();
    bool transactionsIsSet() const;
    void unsetTransactions();

    void setTransactions(const std::vector<std::shared_ptr<GetOneTransaction>>& value);


protected:
    std::vector<std::shared_ptr<GetOneTransaction>> m_Transactions;
    bool m_TransactionsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GetAllTransaction_H_ */
