/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TransactionStatusEnum.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TransactionStatusEnum_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TransactionStatusEnum_H_


#include "naboo/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  TransactionStatusEnum
    : public ModelBase
{
public:
    TransactionStatusEnum();
    virtual ~TransactionStatusEnum();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eTransactionStatusEnum
    {
        TransactionStatusEnum_PENDING,
        TransactionStatusEnum_PAID,
        TransactionStatusEnum_DONE,
        TransactionStatusEnum_PART_PAID,
    };

    eTransactionStatusEnum getValue() const;
    void setValue(eTransactionStatusEnum const value);

    protected:
        eTransactionStatusEnum m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TransactionStatusEnum_H_ */
