/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Wallet.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Wallet_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Wallet_H_


#include "naboo/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  Wallet
    : public ModelBase
{
public:
    Wallet();
    virtual ~Wallet();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eWallet
    {
        Wallet_WAVE,
        Wallet_ORANGE_MONEY,
        Wallet_FREE_MONEY,
    };

    eWallet getValue() const;
    void setValue(eWallet const value);

    protected:
        eWallet m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Wallet_H_ */
